GalleryApp/urls.py
from django.conf.urls import url
from django.contrib import admin
from Gallery import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^album/([0-9]+)/$', views.album, name='album'),
]

Gallery/models.py
from django.db import models

# Create your models here.

ENTITY_STATE = (
    ('delete', 'Deleted'),
    ('active', 'Active'),
    ('inactive', 'Inactive'),
)


class User(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    nick_name = models.CharField(max_length=64)
    external_id = models.CharField(max_length=64)
    state = models.CharField(max_length=16, choices=ENTITY_STATE, default='active')

    def __str__(self):
        if self.nick_name:
            return "'%s'" % (self.nick_name)
        else:
            return "%s %s" % (self.first_name, self.last_name)


class Album(models.Model):
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=512)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    location = models.CharField(max_length=64)
    upload_element_limit = models.IntegerField(null=True)
    upload_size_limit = models.IntegerField(null=True)
    state = models.CharField(max_length=16, choices=ENTITY_STATE, default='active')
    members = models.ManyToManyField(User, through='Participant')

    def __str__(self):
        return self.name


class Participant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    state = models.CharField(max_length=16, choices=ENTITY_STATE, default='active')

    def __str__(self):
        if self.state == 'deleted':
            return "%s %s [deleted]" % (self.user, self.album)
        else:
            return "%s %s" % (self.user, self.album)

    def photos(self):
        return Photo.objects.filter(owner=self)


class Photo(models.Model):
    owner = models.ForeignKey(Participant, on_delete=models.CASCADE, related_name='owned_photos')
    uri = models.CharField(max_length=4096)
    name = models.CharField(max_length=128)
    tag = models.CharField(max_length=128)
    upload_date = models.DateField()
    description = models.CharField(max_length=4096)
    state = models.CharField(max_length=16, choices=ENTITY_STATE, default='active')
    faces = models.ManyToManyField(Participant, verbose_name="list of faces")

    def __str__(self):
        if self.state == 'deleted':
            return "%s: %s[deleted]" % (self.owner, self.name)
        else:
            return "%s: %s" % (self.owner, self.name)

Gallery/views.py
from datetime import datetime
from django.shortcuts import render

from Gallery.facebook import config
from Gallery.models import Album
import logging

# Create your views here.
from django.http import HttpResponse

logger = logging.getLogger(__name__)


def index(request):
    # return HttpResponse("Hello, world. You're at the Gallery index.")
    context = {
        'albums': Album.objects.all(),
        'breadcrumb': [
            {'name': 'Gallery', 'link': "/"},
        ]
    }
    return render(request, 'Gallery/index.html', context)


def album(request, album_id):
    a = Album.objects.get(id=album_id)
    if config.API_KEY in request.COOKIES:
        cookie_value = request.COOKIES[config.API_KEY]
        # request.get_signed_cookie()
        from Gallery.facebook import parse_signed_data
        data = parse_signed_data(cookie_value, config.SALT)
        formatted_date = datetime.fromtimestamp(data['issued_at']).strftime('%Y-%m-%d %H:%M:%S')
        logger.error("Login executed on date %s", formatted_date)
    context = {
        'album': a,
        'breadcrumb': [
            {'name': 'Gallery', 'link': "/"},
            {'name': a.name, 'link': "/album/" + str(a.id) + "/"},
        ]
    }
    return render(request, 'Gallery/album.html', context)

templates/Gallery/album.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gallery</title>
    <link rel="stylesheet" type="text/css" href="{% static 'Gallery/style.css' %}"/>
</head>
<body>
{% include "include/header.html" %}
<h1>{{ album.name }}</h1>
<div class="participant">
    {% for partecipant in album.participant_set.all %}
        <div class='user'>{{ partecipant.user }}
            <div class="photos">
                {% for photo in partecipant.photos %}
                    <a class='photo' href="/photo/{{ photo.id }}/">{{ photo.name }}
                        <img class="image" src="{{ photo.uri }}"/>
                    </a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</div>

templates/Gallery/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gallery</title>
    <link rel="stylesheet" type="text/css" href="{% static 'Gallery/style.css' %}"/>
</head>
<body>
{% include "include/header.html" %}

<!--<div class="logo">

    <img class='globe' src="{% static 'globe.jpg' %}">
    <img class='camera' src="{% static 'camera.gif' %}"></img>
    </img>
</div>
-->
<img class='logo' src="{% static 'Gallery.png' %}"/>
<div id="albums" class="albums">

    {% for album in albums %}
        <a class='album' href="/album/{{ album.id }}/">{{ album.name }}</a>
    {% endfor %}
</div>

</body>
</html>

templates/Gallery/s3-upload/upload.html
<html>
<head>
    <title>Upload Images</title>
    <link rel="stylesheet" href='css/dropzone.css'>
    <style>
        .gallery-bar {
            background-color: black
        }

        .gallery-bar .action a {
            color: orange;
            font-family: Verdana;
            text-decoration: none;
            padding: 4px;
        }

        .gallery-bar .action a:hover {
            background-color: #333;
        }

        .gallery-bar .action {
            padding-left: 10px;
            padding-top: 4px;
            display: inline-block;
        }

        .dropzone {

            /*  max-width: 480px;
              margin-left: auto;
              margin-right: auto;
              */
            border: 2px dashed blue;
            background-color: azure;

        }

        /*
        .dropzone .dz-default.dz-message {
          text-align:center;
          padding:40px;
        }*/
        .dropdown select {
            padding: 8px 20px 8px 8px;

            font-size: 20px;
            font-family: Consolas Menlo Monospace;
        }

        .dropdown {
            padding: 8px;
            font-size: 20px;
            font-family: Consolas Menlo Monospace;
        }
    </style>
</head>
<body style="margin: 0;background-color: gray">

<script src="js/aws-sdk-2.2.30.js">
</script>


<script type="text/javascript">


    // See the Configuring section to configure credentials in the SDK
    //AWS.config.credentials = 1;

    // Configure your region
    AWS.config.region = 'eu-west-1';
    AWS.config.update({
        accessKeyId: 'AKIAI5UUAMAFADCIEVWQ',
        secretAccessKey: 'gbeTrAJgPJ7t6KRJ7trTJdKxEdHY6mveaQg1Z+Xy'
    });

    validateUser = function (select) {
        var e = document.getElementById('my-awesome-dropzone');
        if (select.value !== null && select.value !== undefined && select.value !== '') {
            e.style.display = 'block';
        } else {
            e.style.display = 'none';
        }
    }
</script>

<div id='gallery-bar' class='gallery-bar' style="max-width:100%;position:relative; height: 32px">
    <div class="action"><a href="../index.html">Gallery</a></div>
    <div class="action dropdown"><select id='user' onchange="validateUser(this)">
        <option value=''>Scegli il Cubano:</option>

        <option value='alessandro'>Alessandro</option>
        <option value='angelo'>Angelo</option>
        <option value='annalisa'>Annalisa</option>
        <option value='arianna'>Arianna</option>
        <option value='azzurra'>Azzurra</option>

        <option value='chiara'>Chiara</option>

        <option value='daniele_di_franco'>Daniele di Franco</option>
        <option value='danieleg'>Daniele Galli</option>

        <option value='galassir'>Francesca Galassi</option>
        <option value='ghidoni'>Francesca Ghidoni</option>
        <option value='francesco'>Francesco</option>

        <option value='manuela'>Manuela</option>
        <option value='moniab'>Monia Baiamonte</option>
        <option value='moniag'>Irredentista Cubana</option>

        <option value='roberto'>Roberto</option>

        <option value='sara'>Sara</option>

        <option value='valentina'>Valentina</option>

    </select>
    </div>
</div>
<!--
 <input type="file" id="file-chooser" multiple/> 
    <button id="upload-button">Upload to s3://cuba-discovery</button>-->

<form action='http://cuba-9754.s3.amazonaws.com'
      id="my-awesome-dropzone"
      class='dropzone' style="display:none">

    <div class='fallback'>
        <input type="file" id="file-chooser" multiple/>
        <button id="upload-button">Upload to s3://cuba-discovery</button>
    </div>
</form>
<div id="results"></div>

<script type="text/javascript">


    var bucket = new AWS.S3({
        params: {
            Bucket: 'cuba-9754'
        }
    });

    var fileChooser = document.getElementById('file-chooser');
    var button = document.getElementById('upload-button');
    var results = document.getElementById('results');
    uploadS3 = function (files, dropzone) {
        //var file = fileChooser.files[0];
        if (files) {
            var file = files[0];
            console.log('uploading: ' + file.name + " " + (file.size / (1024 * 1024)));
            //results.innerHTML = '';
            var folder = document.getElementById('user').value;
            var params = {
                Key: 'images/' + folder + '/' + file.name,
                ContentType: file.type,
                Body: file
            };
            var options = {partSize: 10 * 1024 * 1024, queueSize: 1};
            uploader = bucket.upload(params, options, function (err, data) {
                console.log(file.name + ' ' + ( err ? 'ERROR!' : 'UPLOADED.'));
                if (!err) {
                    dropzone._finished([file]);
                }

            });
            uploader.on('httpUploadProgress', function (evt) {
                // console.log('Progress:' + evt.loaded + '/' + evt.total);
                var progress = 100 * (evt.loaded / evt.total);
                var sent = evt.loaded;
                dropzone.options.uploadprogress(file, progress, sent);
            });
            //uploader.send(function(err, data) { console.log(err, data) });
        } else {
            //results.innerHTML = 'Nothing to upload.';
        }
    }
    ;
    button.addEventListener('click', function () {
        uploadS3(fileChooser.files)
    }, false);
</script>
<script src="js/dropzone.js">
</script>
<script type="text/javascript">

    Dropzone.options.myAwesomeDropzone = {
        uploadMultiple: false,
        accept: function (file, done) {
            var lowercaseFilename = file.name.toLowerCase();
            if (lowercaseFilename.endsWith('jpg') || lowercaseFilename.endsWith('jpeg') ||
                    lowercaseFilename.endsWith('mp4') || lowercaseFilename.endsWith('mpg')) {
                done();
            } else {
                done('File extension is not accepted');
            }

        },
        customUpload: uploadS3
    }
</script>
</body>
</html>

templates/include/facebook/facebook.html
<script>
    // This is called with the results from from FB.getLoginStatus().
    function statusChangeCallback(response) {
        console.log('statusChangeCallback');
        console.log(response);
        // The response object is returned with a status field that lets the
        // app know the current login status of the person.
        // Full docs on the response object can be found in the documentation
        // for FB.getLoginStatus().
        if (response.status === 'connected') {
            // Logged into your app and Facebook.
            testAPI();
        } else if (response.status === 'not_authorized') {
            // The person is logged into Facebook, but not your app.
            document.getElementById('status').innerHTML = 'Please log ' +
                    'into this app.';
        } else {
            // The person is not logged into Facebook, so we're not sure if
            // they are logged into this app or not.
            document.getElementById('status').innerHTML = 'Please log ' +
                    'into Facebook.';
        }
    }

    // This function is called when someone finishes with the Login
    // Button.  See the onlogin handler attached to it in the sample
    // code below.
    function checkLoginState() {
        FB.getLoginStatus(function (response) {
            statusChangeCallback(response);
        });
    }

    window.fbAsyncInit = function () {
        FB.init({
            appId: '1786525011604010',
            status: true,
            cookie: true,  // enable cookies to allow the server to access
                           // the session
            xfbml: true,  // parse social plugins on this page
            version: 'v2.7' // use graph api version 2.5
        });

        // Now that we've initialized the JavaScript SDK, we call
        // FB.getLoginStatus().  This function gets the state of the
        // person visiting this page and can return one of three states to
        // the callback you provide.  They can be:
        //
        // 1. Logged into your app ('connected')
        // 2. Logged into Facebook, but not your app ('not_authorized')
        // 3. Not logged into Facebook and can't tell if they are logged into
        //    your app or not.
        //
        // These three cases are handled in the callback function.

        FB.getLoginStatus(function (response) {
            statusChangeCallback(response);
        });

    };

    // Load the SDK asynchronously
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    // Here we run a very simple test of the Graph API after login is
    // successful.  See statusChangeCallback() for when this call is made.
    function testAPI() {
        console.log('Welcome!  Fetching your information.... ');
        FB.api('/me', function (response) {
            console.log('Successful login for: ' + response.name);
            document.getElementById('status').innerHTML =
                    'Thanks for logging in, ' + response.name + '!';
        });
    }
</script>

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->

templates/include/header.html
{% include "include/facebook/facebook.html" %}
<div id="header" class="header">
    <div id="breadcrumbs" class="breadcrumbs">
        {% for step in breadcrumb %}
            <a class="breadcrumb" href="{{ step.link }}">{{ step.name }}</a>
        {% endfor %}
    </div>
    <!--
    <fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
    </fb:login-button>
    -->


    <div id="facebook" class="fb-login-button"
         data-max-rows="1"
         data-size="xlarge"
         data-show-faces="true"
         data-share="true"
         data-auto-logout-link="false"></div>
    <!--    <div id="status"></div>-->
    <a id="upload" class="upload" href="/upload.html/">
        <div class="extra"><img src=""></div>
</div>